config/routes.rb
Rails.application.routes.draw do


  resources :user_profiles do
    member do
      get :profile
      get :publish_article
    end
  end

  devise_for :users

  resources :comments
  resources :articles do
    resources :comments
  end

  root 'user_profiles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, as: :commentable
  belongs_to :user
  has_one_attached :avatar
  enum status: [:is_private, :is_published]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new(commentable_type: "Article", commentable_id: @article.id)
  end
  # GET /articles/new
  def new
    @comment = Comment.new
    @article = Article.new
  end
  # GET /articles/1/edit
  def edit
  end
  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(subject_params)
    respond_to do |format|
      if @article.save!
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end
  def subject_params
    params.required(:article).permit(:article_details, :title, :avatar)
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.fetch(:article, {})
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |form| %>

  <div class="container center_div">
    <h1>New Article</h1>
    <%= form.label("Title") %>
    <%= form.text_field(:title) %>
    <br>
    <%= form.label("Article details") %>
    <%= form.text_field(:article_details) %>
    <br>
    <%= form.file_field :avatar %>
    <br><br>
    <%= form.submit 'Create' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td> <%= article.title %></td>
        <td> <%= article.article_details %></td>
        <td> <%= article.id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Add Comment',new_comment_path(commentable_id:article.id,commentable_type: "Article") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Articles</a>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"  <%= link_to "Home", user_profiles_path %> </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

<div class="jumbotron jumbotron-fluid custom-jumbotron_size border">
  <div class="container">
    <div class="form-row">
      <div class="form-group col-md-2">
        <%= image_tag(@article.avatar, :size => '60x60') %>
      </div>

      <div class="form-group col-md-10">
        <h1 class="display-3"><%= @article.title %></h1>
        <p class="lead"><%= @article.article_details %></p>
        <p>Published at: <%= @article.created_at %></p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Back</a>
      </div>
    </div>

  </div>
</div>

















<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
  <div class="row ">
    <div class="panel panel-default widget col-lg-12">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-comment"></span>
        <h3 class="panel-title ">Recent Comments</h3>
        <span class="label label-info">78</span>
      </div>
      <div id="comments">
        <% @comments.each do |comment| %>
          <%= render 'comments/commentshow', comment: comment %>
        <% end %>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= form_for(@comment, remote: true) do |form| %>
      <%= form.hidden_field(:commentable_id) %>
      <%= form.hidden_field(:commentable_type) %>
      <%= form.label("comment") %>
      <%= form.text_field(:comment_details) %>
      <%= form.submit 'submit' %>
    <% end %>
  <% end %>
</div>